In [34]:
import numpy as np
import pandas as pd
import requests
from datetime import date

In [121]:
df = pd.read_csv('used_cars.csv')
r = requests.get('https://economia.awesomeapi.com.br/last/USD-BRL')

dollar = [r.json()['USDBRL']['bid'], r.json()['USDBRL']['create_date']]
ano = date.today().year
milha = 1.609

In [122]:
df["price"] = df["price"].str.replace('$','')
df["price"] = df["price"].str.replace(',','')

df["milage"] = df["milage"].str.replace('mi.','')
df["milage"] = df["milage"].str.replace(',','')

<ipython-input-122-5483ae0d130a>:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df["price"] = df["price"].str.replace('$','')
<ipython-input-122-5483ae0d130a>:4: FutureWarning: The default value of regex will change from True to False in a future version.
  df["milage"] = df["milage"].str.replace('mi.','')

In [123]:
df["price"] = pd.to_numeric(df["price"], errors= 'coerce')
df["milage"] = pd.to_numeric(df["milage"], errors= 'coerce')

In [124]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4009 entries, 0 to 4008
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   brand         4009 non-null   object
 1   model         4009 non-null   object
 2   model_year    4009 non-null   int64
 3   milage        4009 non-null   int64
 4   fuel_type     3839 non-null   object
 5   engine        4009 non-null   object
 6   transmission  4009 non-null   object
 7   ext_col       4009 non-null   object
 8   int_col       4009 non-null   object
 9   accident      3896 non-null   object
 10  clean_title   3413 non-null   object
 11  price         4009 non-null   int64
dtypes: int64(3), object(9)
memory usage: 376.0+ KB

In [125]:
df['price_converted'] = round(df['price'] * float(dollar[0]), 3)
df['cotacao'] = float(dollar[0])
df['atualizacao_cotacao'] = dollar[1]
df['idade'] = ano - df['model_year']
df['kilometers'] = df['milage'] * milha

In [102]:
dollar[0]

'4.8544'

In [126]:
df.head()

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price,price_converted,cotacao,atualizacao_cotacao,idade,kilometers
0,Ford,Utility Police Interceptor Base,2013,51000,E85 Flex Fuel,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capa...,6-Speed A/T,Black,Black,At least 1 accident or damage reported,Yes,10300,50000.320,4.8544,2023-09-18 19:30:03,10,82059.000
1,Hyundai,Palisade SEL,2021,34742,Gasoline,3.8L V6 24V GDI DOHC,8-Speed Automatic,Moonlight Cloud,Gray,At least 1 accident or damage reported,Yes,38005,184491.472,4.8544,2023-09-18 19:30:03,2,55899.878
2,Lexus,RX 350 RX 350,2022,22372,Gasoline,3.5 Liter DOHC,Automatic,Blue,Black,None reported,NaN,54598,265040.531,4.8544,2023-09-18 19:30:03,1,35996.548
3,INFINITI,Q50 Hybrid Sport,2015,88900,Hybrid,354.0HP 3.5L V6 Cylinder Engine Gas/Electric H...,7-Speed A/T,Black,Black,None reported,Yes,15500,75243.200,4.8544,2023-09-18 19:30:03,8,143040.100
4,Audi,Q3 45 S line Premium Plus,2021,9835,Gasoline,2.0L I4 16V GDI DOHC Turbo,8-Speed Automatic,Glacier White Metallic,Black,None reported,NaN,34999,169899.146,4.8544,2023-09-18 19:30:03,2,15824.515

In [127]:
df.to_csv("car_info.csv")